update sync_dotfiles to not mention dropbox, fix perms

diff --git a/bin/sync_dotfiles b/bin/sync_dotfiles
--- a/bin/sync_dotfiles
+++ b/bin/sync_dotfiles
@@ -1,51 +1,48 @@
 #!/bin/bash
 
 function usage() {
-  echo "usage: sync_dotfiles [-dhnruv] [ -D dropbox-dir ] [ -U home-dir ] "
+  echo "usage: sync_REPODIR [-hnruv] [ -R repo-dir ] [ -H home-dir ] "
   echo "  -h -> show-usage"
-  echo "  -d -> refresh home from dropbox"
   echo "  -n -> no-execute"
-  echo "  -r -> use-remote-home-dir (same as -U $HOME/remote)"
-  echo "  -u -> refresh dropbox from home"
+  echo "  -r -> refresh repo from home"
+  echo "  -u -> refresh user from repo"
   echo "  -v -> verbose"
   exit 1
 }
 
-if [ -d "$HOME/My Documents/My Dropbox" ]
-then
-  dropbox="$HOME/My Documents/My Dropbox"
-elif [ -d "$HOME/Dropbox" -o -L "$HOME/Dropbox" ]
-then
-  dropbox="$HOME/Dropbox"
-else
-  dropbox=/Dropbox
-fi
-dropbox=$dropbox/Shared/dotfiles
-if [ ! -d $dropbox ]
-then
-    echo "Couldn't find your Dropbox dotfiles dir."
-    exit 1
-fi
-
-DHOME=$HOME
+HOMEDIR=$HOME
+REPODIR=/src/dotfiles
 opt_n=0
+opt_r=0
 opt_u=0
-opt_d=0
-opt_v=1
-while getopts dD:hnruU:v arg
+opt_v=0
+while getopts hH:nrR:uU:v arg
 do
   case "$arg" in
-    d) opt_d=1 ;;
-    D) dropbox=$OPTARG ; echo "dropbox = $dropbox" ;;
+    D) REPODIR=$OPTARG ;;
     h) usage   ;;
+    H) HOMEDIR=$OPTARG ;;
     n) opt_n=1 ;;
-    r) DHOME=$HOME/remote ; echo "DHOME = $DHOME" ;;
+    r) opt_r=1 ;;
     u) opt_u=1 ;;
-    U) DHOME=$OPTARG ; echo "DHOME = $DHOME" ;;
     v) opt_v=1 ;;
     *) usage ;;
   esac
 done
+
+if [ ! -d $REPODIR ]
+then
+    echo "Couldn't find your repo dir at $REPODIR."
+    exit 1
+fi
+if [ ! -d $HOMEDIR ]
+then
+    echo "Couldn't find your home dir at $HOMEDIR."
+    exit 1
+fi
+
+echo "HOMEDIR=$HOMEDIR"
+echo "REPODIR=$REPODIR"
 
 function maybe_mkdir() {
     dir="$1"
@@ -69,43 +66,43 @@ function maybe_mkdir() {
 
 function copynewer() {
   f="$1"
-  if [ \( $opt_d -eq 1 \) -o \( \( $opt_u -eq 0 \) -a  "$dropbox/$f" -nt "$DHOME/$f" \) ]
+  if [ \( $opt_r -eq 1 \) -o \( \( $opt_u -eq 0 \) -a  "$REPODIR/$f" -nt "$HOMEDIR/$f" \) ]
   then
     if [ $opt_n -eq 1 -o $opt_v -eq 1 ]
     then
-      echo "dropbox -> home   : $f"
+      echo "repo -> home   : $f"
     fi
     if [ $opt_n -eq 0 ]
     then
-      cp -p "$dropbox/$f" "$DHOME/$f"
+      cp -p "$REPODIR/$f" "$HOMEDIR/$f"
       if [ ! $? ]
       then
-        echo "cp -p \"$dropbox/$f\" \"$DHOME/$f\" failed: $?"
+        echo "cp -p \"$REPODIR/$f\" \"$HOMEDIR/$f\" failed: $?"
         exit $?
       fi
     fi
-  elif [ \( $opt_u -eq 1 \) -o \( "$DHOME/$f" -nt "$dropbox/$f" \) ]
+  elif [ \( $opt_u -eq 1 \) -o \( "$HOMEDIR/$f" -nt "$REPODIR/$f" \) ]
   then
     if [ $opt_n -eq 1 -o $opt_v -eq 1 ]
     then
-     echo "home    -> dropbox: $f"
+     echo "home    -> repo: $f"
     fi
     if [ $opt_n -eq 0 ]
     then
-      cp -p "$DHOME/$f" "$dropbox/$f"
+      cp -p "$HOMEDIR/$f" "$REPODIR/$f"
       if [ ! $? ]
       then
-        echo "cp -p \"$DHOME/$f\" \"$dropbox/$f\" failed: $?"
+        echo "cp -p \"$HOMEDIR/$f\" \"$REPODIR/$f\" failed: $?"
         exit $?
       fi
     fi
   fi
 }
 
-cd "$dropbox"
-for f in $(find . -name .git -prune -o -type f -a \! -name '*.swp' -print)
+cd "$REPODIR"
+for f in $(find . -name .git -prune -o -type f -a \! -name '*.swp' -print | sed -e 's/^..//')
 do
     d=$(dirname "$f")
-    maybe_mkdir "$DHOME/$d"
+    maybe_mkdir "$HOMEDIR/$d"
     copynewer "$f"
 done
