improve symlink handling

diff --git a/bin/sync_dotfiles b/bin/sync_dotfiles
--- a/bin/sync_dotfiles
+++ b/bin/sync_dotfiles
@@ -18,8 +18,9 @@ then
 elif [ -d "$BASEDIR/../.git" ] && \
     grep -q 'url = https://github.com/dpranke/dotfiles' \
     "$BASEDIR/../.git/config"
-  REPODIR=$BASEDIR/..
 then
+  REPODIR=$BASEDIR/..
+else
   REPODIR=$src/dotfiles
 fi
 
@@ -64,23 +65,36 @@ then
 fi
 
 function maybe_mkdir() {
-    dir="$1"
-    if [ \( ! -d "$dir" \) -a \( ! -f "$dir" \) ]
+  dir="$1"
+  if [ \( ! -d "$dir" \) -a \( ! -f "$dir" \) ]
+  then
+    if [ $opt_n -eq 1 -o $opt_v -eq 1 ]
     then
-        if [ $opt_n -eq 1 -o $opt_v -eq 1 ]
-        then
-            echo mkdir -p "$dir"
-        fi
-        if [ $opt_n -eq 0 ]
-        then
-            mkdir -p "$dir"
-            if [ ! $? ]
-            then
-              echo "mkdir -p \"$dir\" failed: $?"
-              exit $?
-            fi
-        fi
+        echo mkdir -p "$dir"
     fi
+    if [ $opt_n -eq 0 ]
+    then
+      mkdir -p "$dir"
+      if [ ! $? ]
+      then
+        echo "mkdir -p \"$dir\" failed: $?"
+        exit $?
+      fi
+    fi
+  fi
+}
+
+function copy() {
+  echo cp -pR "$1" "$2"
+  if [ $opt_n -eq 0 ]
+  then
+    cp -pR "$1" "$2"
+    if [ ! $? ]
+    then
+      echo "  failed: $?"
+      exit $?
+    fi
+  fi
 }
 
 function copynewer() {
@@ -88,41 +102,31 @@ function copynewer() {
   if [ \( $opt_r -eq 1 \) -o \
           \( \( $opt_u -eq 0 \) -a  "$REPODIR/$f" -nt "$HOMEDIR/$f" \) ]
   then
-    echo cp -p "$REPODIR/$f" "$HOMEDIR/$f"
-    if [ $opt_n -eq 0 ]
-    then
-      cp -p "$REPODIR/$f" "$HOMEDIR/$f"
-      if [ ! $? ]
-      then
-        echo "cp -p \"$REPODIR/$f\" \"$HOMEDIR/$f\" failed: $?"
-        exit $?
-      fi
-    fi
+    copy "$REPODIR/$f" "$HOMEDIR/$f"
   elif [ \( $opt_u -eq 1 \) -o \( "$HOMEDIR/$f" -nt "$REPODIR/$f" \) ]
   then
-    echo cp -p "$HOMEDIR/$f" "$REPODIR/$f"
-    if [ $opt_n -eq 0 ]
-    then
-      cp -p "$HOMEDIR/$f" "$REPODIR/$f"
-      if [ ! $? ]
-      then
-        echo "cp -p \"$HOMEDIR/$f\" \"$REPODIR/$f\" failed: $?"
-        exit $?
-      fi
-    fi
+    copy "$HOMEDIR/$f" "$REPODIR/$f"
   fi
 }
 
 cd "$REPODIR"
 for f in $(git ls-files | grep -v '^.gitignore')
 do
-    d=$(dirname "$f")
-    maybe_mkdir "$HOMEDIR/$d"
-    if ! diff -q $HOMEDIR/$f $REPODIR/$f > /dev/null 2> /dev/null
+  d=$(dirname "$f")
+  maybe_mkdir "$HOMEDIR/$d"
+  if [ -h "$REPODIR/$f" ]
+  then
+    # TODO: This doesn't handle the two links pointing to two different
+    # destinations.
+    if [ ! -h "$HOMEDIR/$f" ]
     then
-      copynewer "$f"
-    elif [ $opt_v -eq 1 ]
-    then
-      echo "# $f is up-to-date"
+      copynewer "$REPODIR/$f" "$HOMEDIR/$f"
     fi
+  elif ! diff -q $HOMEDIR/$f $REPODIR/$f > /dev/null 2> /dev/null
+  then
+    copynewer "$f"
+  elif [ $opt_v -eq 1 ]
+  then
+    echo "# $f is up-to-date"
+  fi
 done
